import type { CourseItem } from "../api/courses";
import type { FacultyItem } from "../api/faculty";
import type { SubjectItem } from "../api/subjects";
import type { StudentItem } from "../api/students";
import type { BatchItem } from "../api/batches";
import type { SessionAttendanceRow } from "../api/classSchedule";

export type RootStackParamList = {
  Dashboard: undefined;
  Profile:   undefined;
  BatchList: { initialFilter?: "all" | "active" };
  BatchDetail: { batch: BatchItem };
  CreateBatch: undefined;
  EditBatch: { batch: BatchItem };
  CourseList: undefined;
  CreateCourse: undefined;
  EditCourse: { course: CourseItem };
  FacultyList: undefined;
  CreateFaculty: undefined;
  EditFaculty: { faculty: FacultyItem };
  FacultyAttendance: undefined;
  SubjectList: undefined;
  CreateSubject: undefined;
  EditSubject: { subject: SubjectItem };
  StudentList: { batchId?: string; batchName?: string } | undefined;
  NewAdmission: { applicationId?: string } | undefined;
  EditStudent: { student: StudentItem };
  CenterManagement: undefined;
  StaffManagement:  undefined;
  OrganizationSettings: undefined;
  FeesList:           { initialFilter?: "all" | "active" | "overdue" | "partial" | "completed" } | undefined;
  FeeScheduleDetail:  { enrollmentId: string; studentName: string };
  FeeStructure:       { courseId: string; courseName: string; defaultFee: number };
  Leads: undefined;
  AddLead: undefined;
  AdmissionApplications: undefined;
  Students: undefined;
  BatchSchedule: { batchId: string; batchName: string };
  BatchOffers: { batchId: string; batchName: string };
  SponsorshipDetail: { batchId: string; batchName: string };
  SponsorDetail: { sponsorId: string };
  Sponsors: undefined;
  CreateSponsor: undefined;
  SessionDetail: { sessionId: string; batchId: string; batchName: string };
  TakeAttendance: { sessionId: string; sessionDate: string; roster: SessionAttendanceRow[] };
  Notifications: undefined;
};
